              - name: Setup Java JDK
                uses: actions/setup-java@v4.5.0
            
              - name: Checkout
                uses: actions/checkout@v4.2.2
steps:
- uses: actions/checkout@v4
- uses: actions/setup-java@v4
  with:
    distribution: 'temurin' # See 'Supported distributions' for available options
    java-version: '21'
- run: java HelloWorldApp.java
